docs/AboutUs.md, docs/team/0x4F776C.md
=> Modify AboutUs

docs/AboutUs.md, docs/team/cj-783.md
=> Update about us.md

docs/index.md
=> Update top navbar & index

docs/DeveloperGuide.md
=> Add common terms to glossary list

docs/DeveloperGuide.md
=> Add UC02 and UC06

docs/DeveloperGuide.md
=> Target User, Value Proposition and MVP User Stories

docs/DeveloperGuide.md
Resolves #59, resolves #65, resolves #66, resolves #67
=> Add UC01, UC03, UC04, UC05

src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/SaveCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SaveCommandParser.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Resolves #94
Ping me if there is/are things that I've omitted or included which is not required. Same goes for the comments as well. Thanks!
=> Enhance save feature

docs/DeveloperGuide.md
Removed trailing whitespaces and add fullstops to end of sentences.
=> Resolve minor style issues in Developer Guide

docs/DeveloperGuide.md
This PR includes minor grammatical modification of the existing NFRs.
Resolves #96
=> Modify point 2 of NFRs

docs/DeveloperGuide.md
Updated the glossary to change "Case Sensitive" to "Case Insensitive" as "Case Sensitive" is not used in our documentation
Resolves #97
=> Update glossary user guide

docs/UserGuide.md, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
=> Find contact by phone number

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteByIndexCommand.java, src/main/java/seedu/address/logic/commands/DeleteByPhoneCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/test/java/seedu/address/logic/commands/DeleteByIndexCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteByPhoneCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
=> Add support for deleting contacts by phone number

docs/DeveloperGuide.md
Update the use case.
For Add Contact 
- Changed use case to make it flow better
For deleting phone number
- Amended the use case to follow the one given by the course website as I feel that it flows better.
For saving contacts
- Update the "\<filename\>" to include a backslash as it disappeared in the DeveloperGuide
Do let me know if there's any issue!
Resolves #95
=> Update use case developer guide.md

docs/DeveloperGuide.md
=> Add find contact by phone number use case in developer guide

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java, src/main/java/seedu/address/logic/parser/TagCommandParser.java, src/main/java/seedu/address/logic/parser/UnTagCommandParser.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Fix Tag and UnTag commands ui bugs.
Replace use of Index to tag/untag with Phone number instead.
Also removed 1 unused import in EditCommandTest class.
Resolves #115
=> Enhance tag

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/PreferredContactMethod.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Add email option in the "add" command and made it optional. If user did not specify an email "No email provided." will be shown on the Person's card
- Add a preferred contact method. When user add a contact, the contact will automatically set phone as the default preferred contact method
Resolves #122
=> Enhance Add Feature

src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/SaveCommand.java, src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/JsonAddressBookStorage.java, src/test/java/seedu/address/commons/util/FileUtilTest.java
This commit fixes the issue with save files accumulating in the **./data** directory.
Resolves #121
=> Fix save file accumulation

src/main/java/seedu/address/logic/commands/SaveCommand.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
=> Update testcases for status footer

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml
=> Improve UI for error messages

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java
=> Resolve Project save bugs

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java, src/main/java/seedu/address/model/tag/Tag.java
Updated `MESSAGE_USAGE` for TagCommand and UnTagCommand, among other UI related updates
=> Update Message_Usage for Tag and UnTag Commands

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Update add and edit command usage

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/TagCommandTest.java, src/test/java/seedu/address/logic/commands/UnTagCommandTest.java
Resolve #129 to check if tag/project specified in UnTagCommand exists first.
Fix failing test cases in `TagCommandTest` and `UnTagCommandTest`
=> Enhance Untag Command & Resolve failing test cases

src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedTag.java
This PR is a bug fix to issue #177. Further bug fix is required for switch command @CJ-783.
Test cases will be added in the future.
Resolves #177
=> Fix project load issue

src/main/java/seedu/address/logic/commands/SwitchContactCommand.java
=> Fix tag issue switch command

src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/logic/commands/SnapshotCommand.java, src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/storage/JsonSnapshotStorage.java, src/main/java/seedu/address/storage/SnapshotStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java
This PR adds a new command called "snapshot".
It allows the user to create snapshot of the existing file. It is useful for backup/data migration purpose.
Test cases are failing due to backlogs. Will rectify them in the future.
Resolves #194
=> Add snapshot feature

src/main/java/seedu/address/logic/commands/SwitchContactCommand.java, src/test/java/seedu/address/logic/commands/SaveCommandTest.java, src/test/java/seedu/address/logic/commands/SwitchContactCommandTest.java
=> Improve codecov coverage

docs/diagrams/ModelClassDiagram.puml
=> Update Model Class Diagram

docs/diagrams/BetterModelClassDiagram.puml
=> Update Model Class OOP Diagram in Developer Guide 

docs/UserGuide.md
Resolve #186 
Images can be updated once the UI is finalised in v1.5
=> Update User Guide for Tag/UnTag to consider Project functionality

docs/diagrams/LogicClassDiagram.puml
=> Modify LogicClassDiagram uml

src/main/java/seedu/address/logic/commands/SetStatusCommand.java
Reverts AY2425S2-CS2103-F10-1/tp#225
=> Revert "Amend msgusage setstatus"

docs/diagrams/ModelClassDiagram.puml
=> Uml diagram for OOP

src/main/java/seedu/address/logic/commands/SwitchContactCommand.java, src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java
Change switch contact command from `switchContact` to `switchcontact`
Resolves #237
=> Overzealous Command Input Validation for switchContact

docs/DeveloperGuide.md
=> Add "domain label", "domain" into the glossary list

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/SetStatusCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java
=> Update project prefix

docs/UserGuide.md
Resolves #268
The update on the user guide includes the addition of the new constraints for the `NAME` prefix (ref #255)
=> Update User Guide to add all necessary constraints of prefix into all the command

docs/diagrams/StorageClassDiagram.puml
=> Update storage component diagram in dg

docs/UserGuide.md, src/main/java/seedu/address/model/person/Phone.java, src/test/java/seedu/address/model/person/PhoneTest.java
=> Update application to accept phone numbers starting with "3"

src/main/java/seedu/address/logic/commands/TagCommand.java
=> TagCommand: update message usage string

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/UnTagCommand.java
=> UnTagCommand: report all missing tags and projects in error message

src/main/java/seedu/address/logic/commands/FindCommand.java
=> FindCommand: improve clarity of usage parameters

src/main/java/seedu/address/model/util/SampleDataUtil.java
=> SampleDataUtil: update to reflect current application capabilities

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
=> DeleteCommandParser: improve specificity of error messages

docs/UserGuide.md
Error in Phone constraint & example
=> Update UserGuide to fix constraint for add command in UserGuide

docs/UserGuide.md
Resolve #369 by making `delete` command format similar to `find`
Resolve #324, resolve #348, resolve #351, resolve #381 by making changes to Tag section
Provide example for `DEADLINE` in `setstatus`
=> Update User Guide - Post PE-D

docs/UserGuide.md
This PR include updates made to the user guide for clarity based on feedbacks from PED.
**Changes**
---
`Editing the data file` - resolves #311 
`Saving the data: save` - resolves #334 
`Known issues` - resolves #352 
`Creating snapshot of data: snapshot` - resolves #371
=> remediate issues from PED

src/main/java/seedu/address/logic/parser/ParserUtil.java
=> ParserUtil: improve clarity of error message

src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/SetStatusCommandTest.java, src/test/java/seedu/address/logic/parser/SetStatusCommandParserTest.java, src/test/java/seedu/address/testutil/SetStatusDescriptorBuilder.java
=> Add setstatus related tests

docs/UserGuide.md
Resolves #406
Update done to the help window is on another PR (ref:  #408)
=> Update find command in userguide

src/test/java/seedu/address/model/person/PersonTest.java
Update tests in PersonTest. Has no effect on release JAR.
=> PersonTest: update tests

docs/UserGuide.md
Please check that this didn't break the website too.
=> UserGuide.md: Fix minor formatting issue
